################################################################################
# Playbook: Set up Docker on Ubuntu 20.04 behind a proxy and running containers
################################################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    - name: Install aptitude 
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required packages for Docker set up
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
      
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository for Ubuntu 20.04
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update repository and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
     
############################## In case of being behind a proxy ##################################

# https://docs.docker.com/config/daemon/systemd/#httphttps-proxy
     
    - name: Create Docker Service directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        
    - name: Set up proxy for Docker Service
      template:
        src: "files/http-proxy.conf.j2"
        dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"
      
    - name: Restart Docker Service and also daemon_reload to pick up config changes
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker

##################################################################################################

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
    - name: Install Docker Module for Python
      pip:
        name: docker

    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#ansible-collections-community-docker-docker-image-module
    - name: Pull Docker image
      docker_image:
        name: "{{ container_image }}"
        source: pull

    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module
    - name: Create containers
      docker_container:
        name: "{{ container_name }}{{ item }}"
        image: "{{ container_image }}"
        command: "{{ container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
      
  
          
